### ISSUE TITLE
Deselect / Select

### ISSUE THREAD

**Issue by moiYan** [MaiDaine/gardenly-unity#62]
Quand je click sur le bouton pour créer un ghost handler fleurs, chaise, table le select est appelé.
Quand je click sur un flowerbed le deselect puis le select sont appelé
ça fout la merde dans les open / close view

**Comment by moiYan** [comment]
Ce comportement vient possiblement du fait que le construction state ne passe pas en building mais reste en off lors du click sur un bouton

**Comment by MaiDaine** [comment]
Fix in 617fe87d919d4dfc420e02c1503b2047c0b6a0b8
