### ISSUE TITLE
Queries running after unmount

### ISSUE THREAD

**Issue by BTiers** [MaiDaine/gardenly-unity#78]
Once Unity is unmount (eg: Application.quit() is called) we need to check whether or not queries are still waiting to be resolved.

(Crash)

**Comment by MaiDaine** [comment]
https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationQuit.html
Note: On WebGL it is not possible to implement OnApplicationQuit due to nature of the browser tabs closing.
